// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iit.Data;

#nullable disable

namespace iit.Migrations
{
    [DbContext(typeof(SopalContext))]
    partial class SopalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iit.Models.Fonction", b =>
            {
                b.Property<int>("CodeF")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeF"));

                b.Property<string>("Libelle")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CodeF");

                b.ToTable("Fonctions");
            });
#pragma warning restore 612, 618
        }
    }
}
